# Generated by Django 5.2.6 on 2025-10-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_key', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
