# Generated by Django 5.2.7 on 2025-10-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Circuit')),
                ('map_image_url', models.URLField(blank=True, help_text='Salin dan tempel URL gambar peta sirkuit di sini.', max_length=1024, null=True, verbose_name='Map Image URL')),
                ('map_image_file', models.ImageField(blank=True, editable=False, null=True, upload_to='circuit_maps/', verbose_name='Downloaded Map')),
                ('circuit_type', models.CharField(choices=[('STREET', 'Street circuit'), ('ROAD', 'Road circuit'), ('RACE', 'Race circuit')], default='RACE', max_length=10, verbose_name='Type')),
                ('direction', models.CharField(choices=[('CW', 'Clockwise'), ('ACW', 'Anti-clockwise')], default='CW', max_length=3, verbose_name='Direction')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('last_used', models.IntegerField(blank=True, help_text='Tahun terakhir sirkuit digunakan di F1', null=True, verbose_name='Last used')),
                ('length_km', models.FloatField(help_text='Panjang sirkuit dalam kilometer', verbose_name='Length (km)')),
                ('turns', models.IntegerField(verbose_name='Turns')),
                ('grands_prix', models.CharField(help_text='Nama Grand Prix yang diadakan di sini', max_length=255, verbose_name='Grands Prix')),
                ('seasons', models.CharField(help_text='Contoh: 1985–1995, 2023', max_length=255, verbose_name='Season(s)')),
                ('grands_prix_held', models.IntegerField(verbose_name='Grands Prix held')),
            ],
            options={
                'verbose_name': 'Circuit',
                'verbose_name_plural': 'Circuits',
                'ordering': ['name'],
            },
        ),
    ]
