# Generated by Django 5.2.6 on 2025-10-23 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuit',
            name='map_image_file',
        ),
    ]
