# Generated by Django 5.2.7 on 2025-10-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuit', '0002_remove_circuit_map_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='is_admin_created',
            field=models.BooleanField(default=False, editable=False, help_text='True jika dibuat oleh admin, False jika dari seeder.'),
        ),
    ]
