# Generated by Django 5.2.7 on 2025-11-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuit', '0003_circuit_is_admin_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuit',
            name='last_used',
        ),
    ]
