# Generated by Django 5.2.7 on 2025-10-22 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meeting', '0001_initial'),
        ('session', '0001_initial'),
        ('team', '0002_team_avg_lap_time_ms_team_avg_pit_duration_ms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_number', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=64)),
                ('last_name', models.CharField(blank=True, max_length=64)),
                ('full_name', models.CharField(blank=True, max_length=128)),
                ('broadcast_name', models.CharField(blank=True, help_text='Nama yang ditampilkan di siaran/TV.', max_length=128)),
                ('name_acronym', models.CharField(blank=True, help_text='Tiga huruf akronim (contoh: VER, HAM).', max_length=3)),
                ('country_code', models.CharField(blank=True, max_length=3)),
                ('headshot_url', models.URLField(blank=True)),
                ('biography', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debut_meeting', models.ForeignKey(blank=True, help_text='Meeting pertama (opsional, ringkasan riwayat).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers_debuted', to='meeting.meeting')),
            ],
            options={
                'db_table': 'driver',
                'ordering': ['driver_number'],
            },
        ),
        migrations.CreateModel(
            name='DriverEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_colour', models.CharField(blank=True, help_text='Hex colour pada session ini (RRGGBB).', max_length=6)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='driver.driver')),
                ('meeting', models.ForeignKey(help_text='Meeting yang menaungi session ini.', on_delete=django.db.models.deletion.CASCADE, related_name='driver_entries', to='meeting.meeting')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_entries', to='session.session')),
                ('team', models.ForeignKey(blank=True, help_text='Tim yang dibela pada session ini.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_entries', to='team.team')),
            ],
            options={
                'db_table': 'driver_entry',
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='drivers', through='driver.DriverEntry', to='session.session'),
        ),
        migrations.CreateModel(
            name='DriverTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_colour', models.CharField(blank=True, max_length=6)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_links', to='driver.driver')),
                ('end_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_team_ends', to='meeting.meeting')),
                ('start_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_team_starts', to='meeting.meeting')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_links', to='team.team')),
            ],
            options={
                'db_table': 'driver_team',
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='drivers', through='driver.DriverTeam', to='team.team'),
        ),
        migrations.AddIndex(
            model_name='driverentry',
            index=models.Index(fields=['driver', 'session'], name='driver_entr_driver__d80507_idx'),
        ),
        migrations.AddIndex(
            model_name='driverentry',
            index=models.Index(fields=['meeting'], name='driver_entr_meeting_012d9a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='driverentry',
            unique_together={('driver', 'session')},
        ),
        migrations.AddIndex(
            model_name='driverteam',
            index=models.Index(fields=['driver', 'team'], name='driver_team_driver__3d5c7e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='driverteam',
            unique_together={('driver', 'team', 'start_meeting')},
        ),
    ]
