# Generated by Django 5.2.7 on 2025-10-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_number', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=60)),
                ('last_name', models.CharField(blank=True, max_length=60)),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('broadcast_name', models.CharField(blank=True, max_length=120)),
                ('name_acronym', models.CharField(blank=True, max_length=8)),
                ('country_code', models.CharField(blank=True, max_length=3)),
                ('headshot_url', models.URLField(blank=True)),
                ('meeting_key', models.IntegerField(blank=True, null=True)),
                ('session_key', models.IntegerField(blank=True, null=True)),
                ('team_name', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'driver',
                'ordering': ['driver_number'],
            },
        ),
    ]
