# Generated by Django 5.2.7 on 2025-10-24 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meeting', '0002_alter_meeting_options_meeting_circuit_short_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(db_index=True)),
                ('air_temperature', models.FloatField(blank=True, null=True)),
                ('track_temperature', models.FloatField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('wind_direction', models.IntegerField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('rainfall', models.BooleanField(default=False)),
                ('meeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather_entries', to='meeting.meeting')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('meeting', 'date')},
            },
        ),
    ]
