# Generated by Django 5.2.7 on 2025-10-22 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0001_initial'),
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_number', models.PositiveSmallIntegerField(editable=False, help_text='Nomor urut lap dalam session.', unique=True)),
                ('duration_sector_1', models.FloatField(editable=False, help_text='Waktu sektor 1 lap dalam detik.')),
                ('duration_sector_2', models.FloatField(editable=False, help_text='Waktu sektor 2 lap dalam detik.')),
                ('duration_sector_3', models.FloatField(editable=False, help_text='Waktu sektor 3 lap dalam detik.')),
                ('i1_speed', models.FloatField(editable=False, help_text='Kecepatan pada titik sektor 1 lap (km/h).')),
                ('i2_speed', models.FloatField(editable=False, help_text='Kecepatan pada titik sektor 2 lap (km/h).')),
                ('is_pit_out_lap', models.BooleanField(default=False, editable=False, help_text='Menunjukkan apakah lap ini adalah lap keluar pit.')),
                ('lap_duration', models.FloatField(editable=False, help_text='Total durasi lap dalam detik.')),
                ('segments_sector_1', models.JSONField(blank=True, editable=False, help_text='Mini-sector untuk sektor 1 lap.', null=True)),
                ('segments_sector_2', models.JSONField(blank=True, editable=False, help_text='Mini-sector untuk sektor 2 lap.', null=True)),
                ('segments_sector_3', models.JSONField(blank=True, editable=False, help_text='Mini-sector untuk sektor 3 lap.', null=True)),
                ('st_speed', models.FloatField(blank=True, editable=False, help_text='Kecepatan di titik speed trap (km/h).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(editable=False, help_text='Driver yang melaju pada lap ini.', on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='driver.driver')),
                ('meeting', models.ForeignKey(editable=False, help_text='Meeting tempat lap ini terjadi.', on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='meeting.meeting')),
            ],
            options={
                'db_table': 'laps',
                'ordering': ['lap_number'],
            },
        ),
    ]
