# Generated by Django 5.2.7 on 2025-10-19 06:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laps',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting_key', models.IntegerField()),
                ('session_key', models.IntegerField()),
                ('date_start', models.DateTimeField()),
                ('lap_number', models.PositiveIntegerField()),
                ('duration_sector_1', models.DurationField(blank=True, null=True)),
                ('duration_sector_2', models.DurationField(blank=True, null=True)),
                ('duration_sector_3', models.DurationField(blank=True, null=True)),
                ('lap_duration', models.DurationField(blank=True, null=True)),
                ('i1_speed', models.FloatField(blank=True, null=True)),
                ('i2_speed', models.FloatField(blank=True, null=True)),
                ('st_speed', models.FloatField(blank=True, null=True)),
                ('segments_sector_1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('segments_sector_2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('segments_sector_3', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_out_lap', models.BooleanField(default=False)),
                ('is_pit_out_lap', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='driver.driver')),
            ],
            options={
                'db_table': 'laps',
                'ordering': ['driver__driver_number', 'lap_number'],
                'constraints': [models.UniqueConstraint(fields=('driver', 'session_key', 'lap_number'), name='uniq_lap_per_driver_session')],
            },
        ),
    ]
