# Generated by Django 5.2.7 on 2025-10-22 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laps', '0001_initial'),
        ('pit', '0001_initial'),
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laps',
            name='pit',
            field=models.ForeignKey(blank=True, editable=False, help_text='Relasi ke pit untuk lap ini.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laps', to='pit.pit'),
        ),
        migrations.AddField(
            model_name='laps',
            name='session',
            field=models.ForeignKey(editable=False, help_text='Session tempat lap ini terjadi.', on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='session.session'),
        ),
        migrations.AddConstraint(
            model_name='laps',
            constraint=models.UniqueConstraint(fields=('driver', 'session', 'lap_number'), name='unique_driver_session_lap_number'),
        ),
    ]
