# Generated by Django 5.2.7 on 2025-10-23 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laps', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laps',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='laps',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='laps',
            name='pit',
        ),
        migrations.RemoveField(
            model_name='laps',
            name='session',
        ),
    ]
