# Generated by Django 5.2.7 on 2025-10-23 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laps', '0003_remove_laps_driver_remove_laps_meeting_and_more'),
        ('pit', '0002_delete_pit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Laps',
        ),
    ]
