# Generated by Django 5.2.6 on 2025-10-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('team_colour', models.CharField(max_length=6)),
                ('team_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
