# Generated by Django 5.2.6 on 2025-10-22 01:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='avg_lap_time_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='avg_pit_duration_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='base',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='team',
            name='best_lap_time_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='constructors_championships',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='country',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='drivers_championships',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='engines',
            field=models.TextField(blank=True, help_text='Comma-separated engine supplier list'),
        ),
        migrations.AddField(
            model_name='team',
            name='first_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_first_entered', to='meeting.meeting'),
        ),
        migrations.AddField(
            model_name='team',
            name='founded_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='laps_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='last_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_last_entered', to='meeting.meeting'),
        ),
        migrations.AddField(
            model_name='team',
            name='podiums',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='race_victories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='races_entered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='short_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='team',
            name='team_colour_secondary',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='team',
            name='team_logo_url',
            field=models.TextField(default='https://www.edigitalagency.com.au/wp-content/uploads/F1-logo-png-medium-size.png'),
        ),
        migrations.AddField(
            model_name='team',
            name='top_speed_kph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='team',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='wiki_url',
            field=models.URLField(blank=True),
        ),
    ]
