# Generated by Django 5.2.7 on 2025-10-22 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0001_initial'),
        ('laps', '0001_initial'),
        ('meeting', '0001_initial'),
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pit_duration', models.FloatField(editable=False, help_text='Durasi pit stop (dalam detik).')),
                ('date', models.DateTimeField(editable=False, help_text='Tanggal dan waktu saat pit stop (dalam format ISO 8601).')),
                ('lap_number', models.PositiveSmallIntegerField(editable=False, help_text='Nomor lap tempat pit stop ini terjadi.')),
                ('driver', models.ForeignKey(help_text='Driver yang melakukan pit stop ini.', on_delete=django.db.models.deletion.CASCADE, related_name='pits', to='driver.driver')),
                ('lap', models.ForeignKey(help_text='Lap yang terkait dengan pit stop ini.', on_delete=django.db.models.deletion.CASCADE, related_name='pits', to='laps.laps')),
                ('meeting', models.ForeignKey(help_text='Meeting tempat pit stop ini terjadi.', on_delete=django.db.models.deletion.CASCADE, related_name='pits', to='meeting.meeting')),
                ('session', models.ForeignKey(help_text='Session tempat pit stop ini terjadi.', on_delete=django.db.models.deletion.CASCADE, related_name='pits', to='session.session')),
            ],
            options={
                'db_table': 'pit',
                'ordering': ['lap_number'],
                'constraints': [models.UniqueConstraint(fields=('driver', 'session', 'lap_number'), name='unique_driver_session_lap_number_for_pit')],
            },
        ),
    ]
