# Generated by Django 5.2.7 on 2025-10-19 06:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting_key', models.IntegerField()),
                ('session_key', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('lap_number', models.PositiveIntegerField()),
                ('pit_duration', models.DurationField(blank=True, null=True)),
                ('tire_in', models.CharField(blank=True, max_length=20)),
                ('tire_out', models.CharField(blank=True, max_length=20)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitstops', to='driver.driver')),
            ],
            options={
                'db_table': 'pit',
                'ordering': ['driver__driver_number', 'lap_number'],
                'constraints': [models.UniqueConstraint(fields=('driver', 'session_key', 'lap_number'), name='uniq_pit_per_driver_session')],
            },
        ),
    ]
