# Generated by Django 5.2.6 on 2025-10-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comparison',
            name='title',
            field=models.CharField(default='My Comparison', max_length=100),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='module',
            field=models.CharField(choices=[('team', 'Team'), ('car', 'Car'), ('driver', 'Driver'), ('circuit', 'Circuit')], max_length=20),
        ),
    ]
