# Generated by Django 5.2.6 on 2025-10-24 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuit', '0002_remove_circuit_map_image_file'),
        ('comparison', '0002_comparison_is_public_comparison_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonCircuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circuit.circuit')),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circuit_links', to='comparison.comparison')),
            ],
        ),
    ]
