# Generated by Django 5.2.6 on 2025-10-24 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_car_meeting_session_integer'),
        ('comparison', '0003_comparisoncircuit'),
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_links', to='comparison.comparison')),
            ],
        ),
        migrations.CreateModel(
            name='ComparisonDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_links', to='comparison.comparison')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
            ],
        ),
    ]
