# Generated by Django 5.2.7 on 2025-10-18 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brake', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('date', models.DateTimeField(db_index=True)),
                ('driver_number', models.PositiveSmallIntegerField(db_index=True)),
                ('drs', models.PositiveSmallIntegerField(choices=[(0, 'DRS off'), (1, 'DRS off'), (2, 'Unknown'), (3, 'Unknown'), (8, 'Detected (eligible once in activation zone)'), (9, 'Unknown'), (10, 'DRS on'), (12, 'DRS on'), (13, 'Unknown'), (14, 'DRS on')])),
                ('meeting_key', models.PositiveIntegerField(db_index=True)),
                ('n_gear', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)])),
                ('rpm', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)])),
                ('session_key', models.PositiveIntegerField(db_index=True)),
                ('speed', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(450)])),
                ('throttle', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Car telemetry sample',
                'verbose_name_plural': 'Car telemetry samples',
                'ordering': ['-date'],
                'permissions': [('manage_car_records', 'Can create, update, and delete car telemetry records')],
                'default_permissions': ('view',),
                'indexes': [models.Index(fields=['session_key', 'driver_number', 'date'], name='car_session_driver_ts_idx'), models.Index(fields=['meeting_key', 'driver_number'], name='car_meeting_driver_idx')],
                'constraints': [models.UniqueConstraint(fields=('session_key', 'driver_number', 'date'), name='unique_car_sample_per_timestamp')],
            },
        ),
    ]
