# Generated by Django 5.2.7 on 2025-10-22 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_car_driver'),
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='driver',
            field=models.ForeignKey(blank=True, db_column='driver', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='driver.driver'),
        ),
    ]
