# Generated by Django 5.2.7 on 2025-10-22 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_car_driver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='car',
            name='unique_car_sample_per_timestamp',
        ),
    ]
