# Generated by Django 5.2.7 on 2025-10-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_alter_car_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='car',
            name='car_session_driver_ts_idx',
        ),
        migrations.RemoveIndex(
            model_name='car',
            name='car_meeting_driver_idx',
        ),
    ]
