# Generated by Django 5.2.7 on 2025-10-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_remove_car_car_session_driver_ts_idx_and_more'),
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['session_key', 'driver_number', 'date'], name='car_session_driver_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['meeting_key', 'driver_number'], name='car_meeting_driver_idx'),
        ),
    ]
