# Generated by Django 5.2.7 on 2025-10-23 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_car_link_meeting_session'),
        ('meeting', '0001_initial'),
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='meeting_key',
            field=models.ForeignKey(blank=True, db_column='meeting_key', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='meeting.meeting'),
        ),
        migrations.AlterField(
            model_name='car',
            name='session_key',
            field=models.ForeignKey(blank=True, db_column='session_key', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='session.session'),
        ),
    ]
